<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Krea.Domain\Krea.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="16.1.1"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Features\Commissions\AcceptCommissionRequest\" />
      <Folder Include="Features\Commissions\AddSubmissionFeedback\" />
      <Folder Include="Features\Commissions\AddSubmission\" />
      <Folder Include="Features\Commissions\ApproveCommission\" />
      <Folder Include="Features\Commissions\CancelCommission\" />
      <Folder Include="Features\Commissions\CreateCommissionOffering\" />
      <Folder Include="Features\Commissions\CreateCommissionRequest\" />
      <Folder Include="Features\Commissions\CreatePaymentForCommission\" />
      <Folder Include="Features\Commissions\DeliverCommission\" />
      <Folder Include="Features\Commissions\EditSubmissionFeedback\" />
      <Folder Include="Features\Commissions\RequestChanges\" />
    </ItemGroup>

</Project>
