@API_HostAddress = http://localhost:5101
@auth_token = ACCESS_TOKEN
@userId = GUID_DEL_USUARIO
@postId = GUID_DEL_POST

// Mensajería
@senderId = GUID_DEL_USUARIO
@receiverId = GUID_DEL_USUARIO
@conversationId = GUID_DE_LA_CONV
@messageId = GUID_DEL_MENSAJE

### Register
POST {{API_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "email": "test3@krea.com",
  "username": "testuser3",
  "password": "Test123!",
  "TimezoneId": "1",
  "DisplayName": "testUser3",
  "LanguageCode": "1"
}

### Login
POST {{API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "EmailOrUserName": "testUser3",
  "password": "Test123!"
}

### Login 2
POST http://{{API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "EmailOrUserName": "testUser4",
  "password": "Test123!"
}

### Admin Login
POST http://{{API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "EmailOrUsername": "admin@krea.local",
  "Password": "Admin123!"
}

### ChangePassword
POST http://{{API_HostAddress}}/api/auth/change-password
Content-Type: application/json
Authorization: Bearer <auth_token>

{
  "userId": "GUID",
  "currentPassword": "Test123!",
  "newPassword": "Test124!"
}

### Create Post
POST http://{{API_HostAddress}}/api/posts
Content-Type: application/json

{
  "authorId": "GUID_DEL_USUARIO",
  "title": "Mi primer post",
  "content": "Contenido del post",
  "isWork": false
}

### Get All Posts
GET http://{{API_HostAddress}}/api/posts?page=1&pageSize=10

### Get Post By Id
GET http://{{API_HostAddress}}/api/posts/{{postId}}

### Reply to Post
POST http://{{API_HostAddress}}/api/posts/{{postId}}/reply
Content-Type: application/json

{
  "authorId": "GUID_DEL_USUARIO",
  "title": "Respuesta",
  "content": "Contenido de la respuesta"
}

### Repost
POST http://{{API_HostAddress}}/api/posts/{{postId}}/repost
Content-Type: application/json

{
  "authorId": "GUID_DEL_USUARIO"
}

### Like
POST http://{{API_HostAddress}}/api/posts/{{postId}}/like
Content-Type: application/json

{
  "userId": "GUID_DEL_USUARIO"
}

### Unlike
DELETE http://{{API_HostAddress}}/api/posts/{{postId}}/unlike
Content-Type: application/json

{
  "userId": "GUID_DEL_USUARIO"
}

### Add Upload
POST http://{{API_HostAddress}}/api/posts/{{postId}}/upload
Content-Type: application/json

{
  "mediaId": "GUID_MEDIA",
  "isWorkMedia": false
}



### Send Message
POST http://{{API_HostAddress}}/api/directmessages
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "senderId": "{{senderId}}",
  "receiverId": "{{receiverId}}",
  "content": "Hola, mensaje de prueba"
}

### Get Conversations
GET {{API_HostAddress}}/api/directmessages/conversations
Authorization: Bearer {{auth_token}}

### Get Conversation Messages
GET {{API_HostAddress}}/api/directmessages/conversations/{{conversationId}}/messages?page=1&pageSize=20
Authorization: Bearer {{auth_token}}

### Mark Message As Read
PATCH {{API_HostAddress}}/api/directmessages/{{messageId}}/read
Authorization: Bearer {{auth_token}}
